### ISSUE TITLE
[MPLUGIN-533] Upgrade to Parent 43

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-plugin-tools#842]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** opened **[MPLUGIN-533](https://issues.apache.org/jira/browse/MPLUGIN-533?redirect=false)** and commented

---

**Backported to:** [4.0.0-beta-2](https://github.com/apache/maven-plugin-tools/milestone/4?closed=1), [3.15.0](https://github.com/apache/maven-plugin-tools/milestone/43?closed=1)

**Comment by astramclaren33-code** [comment]
<settings>
  ...
  <profiles>
    ...
    <profile>
      <id>active-profile</id>
      <properties>
        <commons.releaseManagerName>Astra McLaren</commons.releaseManagerName>
        <commons.releaseManagerKey>9fcd58f1-ae14-4072-9727-e82bdbc48ccc</commons.releaseManagerKey>
      </properties>
    </profile>
  </profiles>

  <activeProfiles>
    
    <activeProfile>active-profile</activeProfile>
  </activeProfiles>
  ...
</settings>
